# Generated by Django 5.1.5 on 2025-01-26 18:35

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Fakultet nomi')),
                ('degree', models.CharField(choices=[('bachelor', 'Bakalavr'), ('master', 'Magistratura'), ('doctoral', 'Doctorantura')], max_length=50, verbose_name='Daraja')),
            ],
            options={
                'verbose_name': 'Fakultet',
                'verbose_name_plural': 'Fakultetlar',
            },
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Sport turi')),
            ],
            options={
                'verbose_name': 'Sport turi',
                'verbose_name_plural': 'Sport turlari',
            },
        ),
        migrations.CreateModel(
            name='RegularPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name1', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(2, message="Ism kamida 2 ta belgidan iborat bo'lishi kerak.")], verbose_name='Ism')),
                ('name2', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(3, message="Familiya kamida 3 ta belgidan iborat bo'lishi kerak.")], verbose_name='Familiya')),
                ('name3', models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.MinLengthValidator(3, message="Ota ismi kamida 3 ta belgidan iborat bo'lishi kerak.")], verbose_name='Ota ismi')),
                ('age', models.DateField(verbose_name="Tug'ilgan sana")),
                ('phone', models.CharField(blank=True, max_length=25, verbose_name='Telefon raqam')),
                ('telegram', models.CharField(max_length=255, verbose_name='Telegram')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='Rasm (Avatar)')),
                ('home', models.CharField(max_length=255, verbose_name='Manzil')),
                ('sports', models.ManyToManyField(to='app.sport', verbose_name='Sport turlari')),
            ],
            options={
                'verbose_name': 'Oddiy foydalanuvchi',
                'verbose_name_plural': 'Oddiy foydalanuvchilar',
                'db_table': 'regular_persons_table',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name1', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(2, message="Ism kamida 2 ta belgidan iborat bo'lishi kerak.")], verbose_name='Ism')),
                ('name2', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(3, message="Familiya kamida 3 ta belgidan iborat bo'lishi kerak.")], verbose_name='Familiya')),
                ('name3', models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.MinLengthValidator(3, message="Ota ismi kamida 3 ta belgidan iborat bo'lishi kerak.")], verbose_name='Ota ismi')),
                ('age', models.DateField(verbose_name="Tug'ilgan sana")),
                ('phone', models.CharField(blank=True, max_length=25, verbose_name='Telefon raqam')),
                ('telegram', models.CharField(max_length=255, verbose_name='Telegram')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='Rasm (Avatar)')),
                ('degree', models.CharField(choices=[('bachelor', 'Bakalavr'), ('master', 'Magistratura'), ('doctoral', 'Doctorantura')], max_length=50, verbose_name='Daraja')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.faculty', verbose_name='Fakultet')),
                ('sports', models.ManyToManyField(to='app.sport', verbose_name='Sport turlari')),
            ],
            options={
                'verbose_name': 'Talaba',
                'verbose_name_plural': 'Talabalar',
                'db_table': 'student_form_table',
            },
        ),
    ]
