# Generated by Django 5.1.7 on 2025-03-12 18:34

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademyPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name1', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(2, message="Ism kamida 2 ta belgidan iborat bo'lishi kerak.")], verbose_name='Ism')),
                ('name2', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(3, message="Familiya kamida 3 ta belgidan iborat bo'lishi kerak.")], verbose_name='Familiya')),
                ('name3', models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.MinLengthValidator(3, message="Ota ismi kamida 3 ta belgidan iborat bo'lishi kerak.")], verbose_name='Ota ismi')),
                ('age', models.DateField(verbose_name="Tug'ilgan sana")),
                ('phone', models.CharField(blank=True, max_length=25, verbose_name='Telefon raqam')),
                ('telegram', models.CharField(max_length=255, verbose_name='Telegram')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='Rasm (Avatar)')),
                ('job', models.CharField(max_length=255, verbose_name='Ish joyi')),
                ('position', models.CharField(max_length=255, verbose_name='Lavozimi')),
                ('sports', models.ManyToManyField(to='app.sport', verbose_name='Sport turlari')),
            ],
            options={
                'verbose_name': 'Akademik foydalanuvchi',
                'verbose_name_plural': 'Akademik foydalanuvchilar',
                'db_table': 'academy_persons_table',
            },
        ),
    ]
